### ISSUE TITLE
Fortnite Stats issue.

### ISSUE THREAD

**Issue by flaree** [hatred2k/hatredv3-cogs#1]
Error when using the command fortnite

Exception in command 'fortnite'
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/discord/ext/commands/core.py", line 62, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/home/imtippsyog/.local/share/Red-DiscordBot/cogs/CogManager/cogs/fortnite/fortnite.py", line 111, in fortnite
    data.add_field(name="Time Played", value=stats["lifeTimeStats"][13]["value"])
IndexError: list index out of range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/discord/ext/commands/bot.py", line 886, in invoke
    yield from ctx.command.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/discord/ext/commands/core.py", line 514, in invoke
    yield from injected(*ctx.args, **ctx.kwargs)
  File "/usr/local/lib/python3.5/dist-packages/discord/ext/commands/core.py", line 71, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: IndexError: list index out of range

**Comment by hatred2k** [comment]
@flaree What command did you use? Also what username? Sorry for the late response, haven't had much time lately.

**Comment by flaree** [comment]
[p]fortnite flareeee

Note, I did try with quotations to no prevail.

**Comment by hatred2k** [comment]
There seems to be an issue with retrieving the stats from the fortnite servers. This is something I can’t fix, it’s due to the host/server outages
