### ISSUE TITLE
Unable to load

### ISSUE THREAD

**Issue by KryptoUK** [hatred2k/hatredv3-cogs#7]
You receive an error on install:
`
[15/02/2019 22:59] ERROR core_commands _load 108: Package loading failed
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/redbot/core/core_commands.py", line 104, in _load
    await bot.load_extension(spec)
  File "/usr/local/lib/python3.7/site-packages/redbot/core/bot.py", line 233, in load_extension
    lib = spec.loader.load_module()
  File "<frozen importlib._bootstrap_external>", line 407, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 907, in load_module
  File "<frozen importlib._bootstrap_external>", line 732, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/.local/share/Red-DiscordBot/cogs/CogManager/cogs/fortnite/__init__.py", line 1, in <module>
    from .fortnite import Fortnite
  File "/root/.local/share/Red-DiscordBot/cogs/CogManager/cogs/fortnite/fortnite.py", line 7, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
`

**Comment by hatred2k** [comment]
What OS?

**Comment by KryptoUK** [comment]
I can't recall, but I'm 100% sure it was CentOS

**Comment by hatred2k** [comment]
Try running **yum install python-requests** and then loading it again.
